/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./glb/character.glb");
  const { actions, names } = useAnimations(animations, group);
  console.log(names);
  // // Array(15) [
  //     0'attack1', 1'attack2', 2'attack3', 3'attack4', 4'dead', 5'fall', 6'idle', 7'idle_shield',
  //     8'impact', 9'jump', 10'push', 11'roll', 12'run', 13'run_shield', 14'straf'
  //   ] action names and their indices

  useEffect(() => {
    actions[names[12]].reset().fadeIn(0.5).play();
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="ArmatureCharacter">
          <skinnedMesh
            name="body"
            geometry={nodes.body.geometry}
            material={materials.Material}
            skeleton={nodes.body.skeleton}
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./glb/character.glb");
